### ISSUE TITLE
API request not accepting

### ISSUE THREAD

**Issue by Dhruvsahu9** [natlus08/ClinicalAPI#1]
hi, I made a api request after deploying this code to to aws as a jar file .
the api I hit was this 
------------------------------------------------------------------
___"instance ip"___:8080/clinicalservices/api/patients
------------------------------------------------------------------
but got an whitelabel error can you please specify the correct URI patterns.

**Comment by natlus08** [comment]
Try http://ip:port/clinicals/api/patients, "clinicals" is the context root

**Comment by Dhruvsahu9** [comment]
thanks a lot bro. you have made a great code.Providing a lot of value.
